name: Convert MD to HTML and Commit

on:
  push:
    branches:
      - master  # Trigger on changes to the main branch
  pull_request:
    branches:
      - master  # Trigger for pull requests into the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2  # Checkout the repository's code

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install markdown  # Install the necessary dependencies

    - name: Run the Python script to convert Markdown to HTML
      run: |
        python parsing_script.py  # Replace with your script file name

    - name: Check if there are new or modified HTML files
      id: check_diff
      run: |
        git diff --exit-code -- '*.html' || echo "There are new or modified HTML files."

    - name: Commit and push the HTML files
      if: success()  # Only commit and push if there are changes
      run: |
        git config --global user.email "kevin-email@example.com"
        git config --global user.name "GitHub Action MD->HTML"
        git add *.html
        git commit -m "Add converted HTML files"
        git push origin master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided by GitHub
